apiVersion: kustomize.config.k8s.io/v1beta1
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: tgis-llm-demo
patchesJSON6902:
  - patch: |-
      - op: replace
        path: /spec/targetNamespaces/0
        value: tgis-llm-demo
    target:
      group: operators.coreos.com
      kind: OperatorGroup
      name: redis
      version: v1
resources:
  - ../../base/operators.coreos.com/operatorgroups/redis
  - ../../base/operators.coreos.com/subscriptions/redis
  - ../../base/redisenterprises
  - ../../base/redisenterprisedatabases
  - ../../base/deployments
  - ../../base/services
  - ../../base/configmaps
  - ../../base/persistentvolumeclaims
  - ../../base/routes
  - ../../base/jobs
  - namespaces
secretGenerator:
  - literals:
      - token=PLACEHOLDER
    name: huggingface-hub-token
